DROP TABLE Taking CASCADE CONSTRAINTS;
DROP TABLE Offerings CASCADE CONSTRAINTS;
DROP TABLE Taken CASCADE CONSTRAINTS;
DROP TABLE ReqCourses CASCADE CONSTRAINTS;
DROP TABLE ReqMajor CASCADE CONSTRAINTS;
DROP TABLE Electives CASCADE CONSTRAINTS;
DROP TABLE Students CASCADE CONSTRAINTS;
DROP TABLE Courses CASCADE CONSTRAINTS;
DROP TABLE Term CASCADE CONSTRAINTS;
DROP TABLE Locations CASCADE CONSTRAINTS;
DROP TABLE Professors CASCADE CONSTRAINTS;
DROP TABLE Majors CASCADE CONSTRAINTS;
DROP TABLE QuarterOffered CASCADE CONSTRAINTS;

CREATE TABLE Majors (
    MajorName VARCHAR2(10) PRIMARY KEY,
    dept VARCHAR2(10) NOT NULL,
    num_elect INTEGER NOT NULL
);

CREATE TABLE Professors (
    ID INTEGER PRIMARY KEY,
    Name VARCHAR(20),
    Dept VARCHAR(10)
);

CREATE TABLE Locations (
    Building VARCHAR(7),
    Room VARCHAR(7),
    PRIMARY KEY (Building, Room)
);

CREATE TABLE Students (
    perm VARCHAR2(7) PRIMARY KEY,
    name VARCHAR2(40) NOT NULL,
    address VARCHAR2(40) NOT NULL,
    Dept VARCHAR(10) NOT NULL,
    pin VARCHAR2(64) NOT NULL,
    Major VARCHAR(10) NOT NULL,
    Load INTEGER DEFAULT 0,
    FOREIGN KEY (Major) REFERENCES Majors(MajorName)
);

CREATE TABLE Courses (
    CourseID VARCHAR(7) PRIMARY KEY,
    Title VARCHAR(20),
    enroll_code VARCHAR(7)
);

CREATE TABLE Term (
    TermYear INTEGER,
    Quarter VARCHAR(1),
    PRIMARY KEY (TermYear, Quarter)
);
CREATE TABLE Taken (
    TCourseID VARCHAR(7),
    StudentPerm VARCHAR2(7),
    TakenYear INTEGER NOT NULL,
    Quarter VARCHAR(1) NOT NULL,
    grade VARCHAR(2) NOT NULL,
    PRIMARY KEY (TCourseID, StudentPerm, TakenYear, Quarter),
    FOREIGN KEY (StudentPerm) REFERENCES Students(perm) ON DELETE CASCADE,
    FOREIGN KEY (TCourseID) REFERENCES Courses(CourseID),
    FOREIGN KEY (TakenYear, Quarter) REFERENCES Term(TermYear, Quarter)
);
CREATE TABLE QuarterOffered (
    CourseID VARCHAR2(7),
    Quarter VARCHAR2(1),  -- 'W', 'S', 'F'
    
    PRIMARY KEY (CourseID, Quarter),
    FOREIGN KEY (CourseID) REFERENCES Courses(CourseID)
);


CREATE TABLE Offerings (
    OfferingID INTEGER PRIMARY KEY,
    CourseID VARCHAR(7),
    Prof INTEGER,
    Building VARCHAR(7),
    Room VARCHAR(7),
    Quarter VARCHAR(1),
    Year INTEGER,
    Day VARCHAR(9),
    Capacity INTEGER,
    Timeslot VARCHAR(10),
    FOREIGN KEY (Year, Quarter) REFERENCES Term(TermYear, Quarter),
    FOREIGN KEY (CourseID) REFERENCES Courses(CourseID) ON DELETE CASCADE,
    FOREIGN KEY (Building, Room) REFERENCES Locations(Building, Room) ON DELETE CASCADE,
    FOREIGN KEY (Prof) REFERENCES Professors(ID),
    FOREIGN KEY (CourseID, Quarter) REFERENCES QuarterOffered ON DELETE CASCADE
);

CREATE TABLE Taking (
    OfferingID INTEGER,
    StudentPerm VARCHAR2(7),
    CourseID VARCHAR(7),
    PRIMARY KEY (OfferingID, StudentPerm, CourseID),
    FOREIGN KEY (CourseID) REFERENCES Courses(CourseID) ON DELETE CASCADE,
    FOREIGN KEY (StudentPerm) REFERENCES Students(perm) ON DELETE CASCADE,
    FOREIGN KEY (OfferingID) REFERENCES Offerings(OfferingID) ON DELETE CASCADE
);

CREATE TABLE Electives (
    MajorName VARCHAR2(10),
    CourseID VARCHAR(7),
    PRIMARY KEY (MajorName, CourseID),
    FOREIGN KEY (MajorName) REFERENCES Majors(MajorName) ON DELETE CASCADE,
    FOREIGN KEY (CourseID) REFERENCES Courses(CourseID) ON DELETE CASCADE
);

CREATE TABLE ReqMajor (
    MajorName VARCHAR2(10),
    CourseID VARCHAR(7),
    PRIMARY KEY (MajorName, CourseID),
    FOREIGN KEY (MajorName) REFERENCES Majors(MajorName) ON DELETE CASCADE,
    FOREIGN KEY (CourseID) REFERENCES Courses(CourseID) ON DELETE CASCADE
);

CREATE TABLE ReqCourses (
    CourseID1 VARCHAR2(7),
    CourseID2 VARCHAR(7),
    PRIMARY KEY (CourseID1, CourseID2),
    FOREIGN KEY (CourseID1) REFERENCES Courses(CourseID) ON DELETE CASCADE,
    FOREIGN KEY (CourseID2) REFERENCES Courses(CourseID) ON DELETE CASCADE
);



CREATE OR REPLACE TRIGGER set_student_load_to_zero
BEFORE INSERT ON Students
FOR EACH ROW
BEGIN
    :NEW.Load := 0;
END;
/
CREATE OR REPLACE TRIGGER increment_load_on_insert
BEFORE INSERT ON Taking
FOR EACH ROW
DECLARE
    current_load INTEGER;
BEGIN

    SELECT Load INTO current_load FROM Students WHERE perm = :NEW.StudentPerm;


    IF current_load >= 5 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Student cannot enroll in more than 5 courses.');
    END IF;

    UPDATE Students
    SET Load = Load + 1
    WHERE perm = :NEW.StudentPerm;
END;
/
CREATE OR REPLACE TRIGGER decrement_load_on_delete
AFTER DELETE ON Taking
FOR EACH ROW
BEGIN
    UPDATE Students
    SET Load = Load - 1
    WHERE perm = :OLD.StudentPerm;
END;
/


CREATE OR REPLACE FUNCTION VerifyPin(
    p_perm IN VARCHAR2,
    p_pin  IN VARCHAR2
) RETURN NUMBER IS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM STUDENTS
    WHERE perm = p_perm AND pin = p_pin;

    RETURN CASE WHEN v_count = 1 THEN 1 ELSE 0 END;
END;
/


CREATE OR REPLACE FUNCTION SetPin(
    p_perm       IN VARCHAR2,
    p_oldpin     IN VARCHAR2,
    p_newpin     IN VARCHAR2
) RETURN NUMBER IS
BEGIN
    -- check if old PIN matches
    IF VerifyPin(p_perm, p_oldpin) = 1 THEN
        UPDATE STUDENTS
        SET pin = p_newpin
        WHERE perm = p_perm;
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;
END;
/



--GRANT CREATE SESSION TO STUDENT_ACCESS;
--
--
--GRANT SELECT ON STUDENTINFO TO STUDENT_ACCESS;
--GRANT SELECT ON STUDENTS TO STUDENT_ACCESS;
--GRANT SELECT ON ADMIN.STUDENTOFFERING TO STUDENT_ACCESS;
GRANT SELECT ON ADMIN.STUDENTOFFERING TO STUDENT_ACCESS;
--REVOKE INSERT ON ADMIN.STUDENTTAKEN FROM STUDENT_ACCESS;
GRANT SELECT ON ADMIN.STUDENTTAKEN TO STUDENT_ACCESS;

GRANT SELECT ON ADMIN.TAKING TO STUDENT_ACCESS;
GRANT INSERT ON ADMIN.TAKING TO STUDENT_ACCESS;
GRANT DELETE ON ADMIN.TAKING TO STUDENT_ACCESS;
GRANT SELECT ON ADMIN.REQCOURSES TO STUDENT_ACCESS;

GRANT SELECT ON ADMIN.TAKING TO STUDENT_ACCESS;
GRANT SELECT ON ADMIN.STUDENTELECTIVES TO STUDENT_ACCESS;
GRANT SELECT ON ADMIN.STUDENTMAJORS TO STUDENT_ACCESS;
GRANT SELECT ON ADMIN.STUDENTREQMAJOR TO STUDENT_ACCESS;
GRANT SELECT ON ADMIN.STUDENTCOURSES TO STUDENT_ACCESS;
GRANT SELECT ON ADMIN.STUDENTTAKEN TO STUDENT_ACCESS;
GRANT INSERT ON ADMIN.TAKING TO STUDENT_ACCESS;
GRANT DELETE ON ADMIN.TAKING TO STUDENT_ACCESS;
GRANT SELECT ON ADMIN.REQCOURSES TO STUDENT_ACCESS;
GRANT SELECT ON ADMIN.STUDENTREQCOURSES to STUDENT_ACCESS;
GRANT SELECT ON ADMIN.STUDENTOFFERING TO STUDENT_ACCESS;
GRANT SELECT ON ADMIN.STUDENTOFFERING TO REGENT;
GRANT SELECT ON ADMIN.STUDENTTAKING TO REGENT;
GRANT SELECT ON ADMIN.ReqCourses TO REGENT;
GRANT INSERT ON ADMIN.TAKEN TO REGENT;
GRANT INSERT ON ADMIN.TAKING TO REGENT;
GRANT SELECT ON ADMIN.TAKING TO REGENT;
GRANT SELECT ON ADMIN.TERM TO REGENT;
GRANT SELECT ON ADMIN.TAKEN TO REGENT;
GRANT DELETE ON ADMIN.TAKING TO REGENT;
GRANT SELECT ON ADMIN.STUDENTTAKEN TO REGENT;
GRANT SELECT ON ADMIN.STUDENTINFO TO REGENT;
GRANT SELECT ON ADMIN.QuarterOffered TO REGENT;
GRANT SELECT ON ADMIN.QuarterOffered TO STUDENT_ACCESS;
GRANT SELECT ON STUDENTOFFERING TO STUDENT_ACCESS;
GRANT EXECUTE ON VerifyPin TO STUDENT_ACCESS;
GRANT EXECUTE ON Setpin TO STUDENT_ACCESS;

--GRANT SELECT, INSERT, DELETE ON ADMIN.STUDENTTAKEN TO STUDENT_ACCESS;
--

--CREATE USER regent IDENTIFIED BY Somebodyplease2#;
-- GRANT CONNECT, RESOURCE TO regent;
